import { ApiProperty } from '@nestjs/swagger';
import { Entity, PrimaryGeneratedColumn, ManyToOne } from 'typeorm';
import UserEntity from './users.entity';

@Entity({ name: 'friends' })
export default class FriendsEntity {
  @ApiProperty({
    type: Number,
    example: 54,
    description: 'Primary autogenerated key of the table',
  })
  @PrimaryGeneratedColumn()
  public id: number;

  @ApiProperty({
    type: () => UserEntity,
    example: '[Arkadiy, Serega, Khamil]',
    description: 'Friend of the current user',
  })
  @ManyToOne(() => UserEntity, (user) => user)
  public friends: UserEntity;
}
