import { ApiProperty } from '@nestjs/swagger';
import { Entity, PrimaryGeneratedColumn, ManyToOne, Column } from 'typeorm';
import UserEntity from './users.entity';

@Entity({ name: 'friends' })
export default class FriendsEntity {
  @ApiProperty({
    type: Number,
    example: 54,
    description: 'Primary autogenerated key of the table',
  })
  @PrimaryGeneratedColumn()
  public id: number;

  @ApiProperty({
    type: String,
    example: 'Arkadiy',
    description: 'Username of the current friend of that user',
  })
  @Column({ type: 'varchar', nullable: false })
  public username: string;

  @ApiProperty({
    type: () => UserEntity,
    example: '[Arkadiy, Serega, Khamil]',
    description: 'Friend of the current user',
  })
  @ManyToOne(() => UserEntity, (user) => user, { onDelete: 'CASCADE' })
  public friends: UserEntity;
}
