import { ApiProperty } from '@nestjs/swagger';
import { Entity, PrimaryGeneratedColumn, ManyToOne } from 'typeorm';
import UserEntity from './users.entity';

@Entity({ name: 'friends' })
export default class FriendsEntity {
  @ApiProperty({
    type: Number,
    example: 54,
    description: 'Primary autogenerated key of the table',
  })
  @PrimaryGeneratedColumn()
  public id: number;

  @ApiProperty({
    type: () => UserEntity,
    example: 'Petya',
    description: 'User, which is friend of the another user',
  })
  @ManyToOne(() => UserEntity, (user) => user.friends)
  public user: UserEntity;
}
