import UserEntity from '../../users/entities/users.entity';
import { Entity, PrimaryGeneratedColumn, Column, OneToOne } from 'typeorm';
import { ApiProperty } from '@nestjs/swagger';

@Entity({ name: 'jwt_token' })
export default class JwtTokenEntity {
  @ApiProperty({
    type: Number,
    example: 23,
    description: 'Primary autogenerated key of the table',
  })
  @PrimaryGeneratedColumn()
  public id: number;

  @ApiProperty({
    type: String,
    example: '^fg@hsjcn@387fXa',
    description: 'Refresh Token',
  })
  @Column({ type: String, nullable: false })
  public token: string;

  @ApiProperty({
    type: () => UserEntity,
    example: 'Arkadiy',
    description: 'User, which has that token',
  })
  @OneToOne(() => UserEntity, (user) => user.refreshToken)
  public user: UserEntity;
}
