import { Column, Entity, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import { ApiProperty } from '@nestjs/swagger';
import UserEntity from 'src/users/entities/users.entity';

@Entity({ name: 'invites' })
export default class InviteEntity {
  @ApiProperty({
    type: Number,
    example: 20,
    description: 'Primary autogenerated key',
  })
  @PrimaryGeneratedColumn()
  public id: number;

  @ApiProperty({
    type: String,
    example: "Hello, can I become you'r friend? :)",
    description: '',
  })
  @Column({ type: 'varchar', nullable: false })
  public text: string;

  @ApiProperty({
    type: () => UserEntity,
    example: 'Sergey',
    description: 'Man, who send a current invite to the friends',
  })
  @ManyToOne(() => UserEntity, (user) => user.username, { onDelete: 'CASCADE' })
  public sender: string;

  @ApiProperty({
    type: () => UserEntity,
    example: 'Arkadiy',
    description: 'User, which catch a current invite form another user',
  })
  @ManyToOne(() => UserEntity, (user) => user.username, { onDelete: 'CASCADE' })
  public catcher: string;
}
